---
- name: install nginx
  hosts: SecondLab
  become: yes

  tasks:
    - name: package update
      yum:
        name: '*'
        state: latest
    - name: install nginx
      yum:
        name: nginx
        state: present
    - name: nginx start
      service:
        name: nginx
        state: started
    
    